
#################################### Instance #####################################
# instance.name: server
# instance.port: 8699

################################### Cluster #######################################
# Cluster name identifies your cluster for auto-discovery. If you're running
# multiple clusters on the same network, make sure you're using unique names.
#
# cluster.name: openesb

##################################### HTTP ########################################
# Set a custom port to listen for HTTP traffic:
#
# http.port: 4848

# Disable HTTP completely:
#
# http.enabled: false

##################################### JNDI ########################################
# Specify the context file to used for JNDI
# jndi.context: ${install.root}/config/context.xml

################################### Security ######################################
# Set the security realms which have to be used for management purpose or components
# security concerns.
realm:
   # The realm "admin" is the realm used for management (JMX / Rest API)
   admin:
      type: properties
      file: ${install.root}/config/mgmt-users.properties